@startuml
actor android [
    android user
]
actor apple [
    apple user
]
actor browser
agent server [
    web server
]

database db
queue queue
cloud foo  {
    artifact RESTful
    artifact mvc
}
artifact RESTful_client [
    RESTful client
]
artifact service_api [
     service api
]
artifact service_impl [
    service impl
]
artifact dao
artifact lang
android -- server
apple -- server
browser -- server
server -- mvc : request/response
server -- RESTful : request/response
RESTful_client -- RESTful
RESTful -- service_api : DTO
mvc -- service_api : DTO
service_api -- service_impl
service_impl -- lang
service_impl -- dao
dao -- db
dao -- queue
@enduml